sudo: required
dist: trusty

#install google chrome, using addons
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable


env:
  global:
language: node_js
node_js:
  - "8"
before_install:
  - composer config --global github-oauth.github.com "$GITHUB_TOKEN"
  
before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --global gulp --save
  - gem install sass
  - npm install
  - npm install d3@^5.7.0
  - ng build --prod amexio-chart-d3 && sh copycss.sh
  - npm pack dist/amexio-chart-d3/
  - mv amexio-chart-d3-*.tgz amexio-chart-d3.tgz   
script: 
  - git clone https://github.com/meta-magic/amexio-ios.git -b v5.4-dec
  - cd amexio-ios
  - cp -rf ../amexio-chart-d3.tgz .
  - git add amexio-chart-d3.tgz
  - git commit -m "date"
  - git push --force --quiet "https://deepali-arvind:${GITHUB_TOKEN}@github.com/${GITHUB_REPO}.git" HEAD:v5.4-dec
after_success: 
  - codecov
cache:
  yarn: true
